# Model Arguments
encoder_type: mcvit
in_channels: 6
use_instance_norm: true
hidden_size: 384        # ViT-S
num_hidden_layers: 12
num_attention_heads: 6
image_size: 224
patch_size: 16
use_flash_attention: true
temperature: 0.07
projection_dim: 128
projection_hidden_dim: 2048
pretrained_vit: false

# Data Arguments
dataset: rxrx3
csv_path: <path_to_rxrx3_full_metadata>
img_folder: <path_to_rxrx3_images>
train_split: train


# Training Arguments
output_dir: ../ckpt/simclr_vits_rxrx3_batch
num_train_epochs: 200
per_device_train_batch_size: 512
learning_rate: 1e-4                   
weight_decay: 0.01
warmup_ratio: 0.1
lr_scheduler_type: cosine
logging_steps: 50
save_strategy: epoch
save_total_limit: 10
dataloader_num_workers: 16
dataloader_persistent_workers: true
bf16: true                            # Use bf16 if available
dataloader_pin_memory: true
remove_unused_columns: false          
report_to: wandb                     
run_name: simclr_vits_rxrx3